FROM ubuntu:22.04

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
        bash \
        bash-completion \
        curl \
        git \
        iputils-ping \
        jq \
        make \
        pandoc \
        shellcheck \
        tig \
        tmate \
        vim \
 && true
